# Generated by Django 4.2.8 on 2024-01-18 15:18

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='İsim')),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Nekadar Bağış Yapıldı')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Eklenme tarihi')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('donation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.donationtype', verbose_name='Aylık / Tek Seferlik Ödeme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kim Bağış Yaptı')),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to=user_app.models.image_dir_path, verbose_name='kapak resmi')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('slug', models.SlugField(default='Slug ismi')),
                ('content', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(verbose_name='aktifmi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yazar')),
            ],
        ),
    ]
